### ISSUE TITLE
about the ipot_demo.py

### ISSUE THREAD

**Issue by young1234567** [xieyujia/IPOT#1]
when i run the code of ipot_demo.py, i found that the code misses a tuple named "epsilon_list[i]", could you tell me if it's missed by mistake ?
thanks a lot

**Comment by lqzhao** [comment]
Hi, have you figured out this problem? Thanks. @xieyujia @young1234567

**Comment by xieyujia** [comment]
Hi,
It should be `beta_list` instead of `epsilon_list`. I have fix the bug. 
Thanks for pointing it out!
